#!/usr/bin/env bash

set -e

declare -A repos=([llvm]=llvm-mirror \
       [clang]=llvm-mirror \
       [lld]=llvm-mirror \
       [clang-tools-extra]=llvm-mirror \
       [compiler-rt]=llvm-mirror [libcxx]=llvm-mirror \
       [libcxxabi]=llvm-mirror \
       [libunwind]=llvm-mirror \
       [lldb]=llvm-mirror)

declare -A branches=()

echo "{ fetchFromGitHub }: {"

for repo in "${!repos[@]}"; do
    owner=${repos[$repo]}

    echo git@github.com:$owner/$repo >&2
    if [ ! -d llvm-mirror/$repo ]; then
	git clone -q git@github.com:$owner/$repo llvm-mirror/$repo
    fi

    GIT="git --work-tree llvm-mirror/$repo --git-dir llvm-mirror/$repo/.git"

    if [ x$1 != x"--dont-pull" ]; then
        branch=${branches[$repo]}
	$GIT fetch -q
	$GIT checkout -q $branch
	$GIT pull -q origin
    fi
    rev=$($GIT rev-parse HEAD)
    sha=$(nix-prefetch-url --unpack https://github.com/$owner/$repo/archive/$rev.tar.gz)
    echo "  $repo = fetchFromGitHub {"
    echo "    owner = \"$owner\";"
    echo "    repo = \"$repo\";"
    echo "    rev = \"$rev\";"
    echo "    sha256 = \"$sha\";"
    echo "  };"
done

echo "}"
