# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-2.6.1" = {
      name = "async";
      packageName = "async";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.1.tgz";
        sha512 = "2aqgkis9ac37q6jv6zspfpj3rikh2vr9fdch7wajrvqihq5sxyd1gh5zv65hy0y3r22l720qkidwh6img8dngqcjj0dwrl0dwpj5lbw";
      };
    };
    "browserfs-1.4.3" = {
      name = "browserfs";
      packageName = "browserfs";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserfs/-/browserfs-1.4.3.tgz";
        sha512 = "39jq7fphcz7kwfcwqb7iiy3b47gfihlyhy5mr9rjdvj6d32kxzvlbzywp5wdcqpwjsqn16wm275qphkxg3vp26chmn35kbbal50fgxp";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "1ba5b80jjzwrh9fbdk5ywv8sic0dynij21wgrfxsfjzwvwd7x1n6azdhdc0vjdxqmcpm0mhshd1k7n2ascxpz00z3p8a3k97mwg1s2i";
      };
    };
    "pako-1.0.6" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.6.tgz";
        sha512 = "1r9hy37qsbhv5ipsydkbir2yl7qg3lbpgj4qzrnb903w8mhj9ibaww0zykbp0ak1nxxp6mpbws3xsrf7fgq39zchci90c7chgqvh1wm";
      };
    };
  };
  args = {
    name = "webabi";
    packageName = "webabi";
    version = "0.0.1";
    src = builtins.fetchGit https://github.com/zw3rk/webabi;
    dependencies = [
      sources."async-2.6.1"
      sources."browserfs-1.4.3"
      sources."lodash-4.17.10"
      sources."pako-1.0.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
